### ISSUE TITLE
lastModified does not exist on Directory with Laravel 9

### ISSUE THREAD

**Issue by timramseyjr** [mafftor/laravel-file-manager#11]
* Operating system : Ubuntu 20.04
 * Laravel version : 9.25.1
 * Package version : 2.0.10
 * Steps to reproduce your issue : Create a folder and refresh the page when using Laravel 9

`Unable to retrieve the last_modified for file at location: public/uploads.  {"userId":1,"exception":"[object] (League\\Flysystem\\UnableToRetrieveMetadata(code: 0): Unable to retrieve the last_modified for file at location: public/uploads.  at /home/examplel/vendor/league/flysystem/src/UnableToRetrieveMetadata.php:49)`

The issue is coming from `vendor/mafftor/laravel-file-manager/src/LfmItem.php:141 Mafftor\LaravelFileManager\LfmItem::time` where lastModified does not exist for the directory

Looks like it is the same thing as https://github.com/UniSharp/laravel-filemanager/issues/1135

**Comment by mafftor** [comment]
Huge thanks! Will look at this asap!

**Comment by mafftor** [comment]
Hi @timramseyjr !
What storage driver do you use?
Is that classic 'local' one?

```php
'local' => [
    'driver' => 'local',
    'root' => storage_path('app'),
    'throw' => false,
],
```

**Comment by mafftor** [comment]
@timramseyjr I've published it, could you pull the master branch and test it? Thanks in advance!

**Comment by mafftor** [comment]
Closing the ticket with no tests, in case the problem appears, please open the new one!
The change will be available in the new release

**Comment by timramseyjr** [comment]
@mafftor I will test it out this week. The issue was with S3 since a `last_modified` attribute for directories is not returned anymore.

**Comment by mafftor** [comment]
Great! I've added a try-catch block to return null if the file driver does not support last modified attribute
