### ISSUE TITLE
Search functionality would be a great feature.

### ISSUE THREAD

**Issue by afrazahmmad** [mafftor/laravel-file-manager#17]
Can you please add search functionality for files and folders ?

this will be very helpful when file manger has large number files

**Comment by mafftor** [comment]
HI! The Search feature already exists
<img width="1451" alt="image" src="https://github.com/mafftor/laravel-file-manager/assets/7810087/c1938cef-3bd6-46fe-a9e7-1490375d5bc8">
Try to update your package or update config file (take fresh from package)
