### ISSUE TITLE
Thumbnails in ftp connection

### ISSUE THREAD

**Issue by nunofmmarques** [mafftor/laravel-file-manager#5]
I'm building CMS with multiple websites where each one can be on a different serve, so I'm using the ftp storage with the filemanager.
The thing is that the thumbnais don't load because they are not in the CMS domain...
On the file script.js i needed to have the website url.
Any ideia how i could do this?
``var image = $('<div>').css('background-image', 'url(URL + item.thumb_url + '?timestamp=' + item.time + '")');``

**Comment by mafftor** [comment]
Hello!
Firstly, I need to see your `lfm.php` config file.
Secondly, I guess you should define the URL of your FTP storage in `filesystems.php` config file

Something like this
```php
'disks' => [
    ..........
    ..........

    'myFtpDisk' => [

        ...........

        'url' => 'my-ftp.example.com',
    ],
],
```

**Comment by nunofmmarques** [comment]
This worked! I didn't know about this option...
Thank you!
