### ISSUE TITLE
Cannot override the file

### ISSUE THREAD

**Issue by shahruslan** [mafftor/laravel-file-manager#6]
You use scripts from the /public/vendor folder everywhere. And at this point you are using a script from your repository that cannot be overridden.

https://github.com/mafftor/laravel-file-manager/blob/8d8bfdd73991f5d8925196d1246b1305ae0510b9/src/views/index.blade.php#L229

**Comment by mafftor** [comment]
@shahruslan Ruslan, thanks. 
I know it but this solution from the origin repository, later I'll change it if it's necessary

**Comment by mafftor** [comment]
@shahruslan You can `php artisan vendor:publish --tag=lfm_view` publish the views and change if you need.
Anyway I've fixed
